import linkage_complete_intersections_determinantal_ideals_theorem_canonical_lane_mathlib.GateLemmas
import linkage_complete_intersections_determinantal_ideals_theorem_canonical_lane_mathlib.FinalTheorem
